# permissions for end users to edit nestedcontrollermanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nestedcontrollermanager-editor-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - nestedcontrollermanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - nestedcontrollermanagers/status
  verbs:
  - get
