apiVersion: v1
kind: Service
metadata:
  name: {{.clusterName}}-apiserver
  namespace: {{.componentNamespace}}
  labels: 
    component-name: {{.componentName}}
spec:
  selector:
    component-name: {{.componentName}}
  type: ClusterIP
  ports:
  - name: api
    port: 6443
    protocol: TCP
    targetPort: api
