apiVersion: v1
kind: Service
metadata:
  name: {{.clusterName}}-etcd
  namespace: {{.componentNamespace}}
  labels:
    component-name: {{.componentName}} 
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    component-name: {{.componentName}}
