apiVersion: v1
kind: Service
metadata:
  name: {{.nestedetcdName}}
  namespace: {{.nestedetcdNamespace}}
  labels:
    component-name: {{.nestedetcdName}} 
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    component-name: {{.nestedetcdName}}
