# permissions for end users to view nestedcontrollermanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nestedcontrollermanager-viewer-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - nestedcontrollermanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - nestedcontrollermanagers/status
  verbs:
  - get
